# Generated by Django 2.2 on 2023-03-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
